### ISSUE TITLE
upgrade to beancount v3

### ISSUE THREAD

**Issue by maxheld83** [dallaslu/beancount-periodic#4]
I just tried playing with beancount v3, and it appears (?) that `beancount-periodic` does not play nice with beancount v3:

after running `pip install git+https://github.com/beancount/beancount.git`, on

```
; test.bean

plugin "beancount_periodic.depreciate"

```

I get:

```
      from beancount.utils.date_utils import parse_date_liberally
  ImportError: cannot import name 'parse_date_liberally' from 'beancount.utils.date_utils' (/opt/homebrew/lib/python3.11/site-packages/beancount/utils/date_utils.py)
```

Am I interpreting this correctly that `beancount_periodic` is calling some API from beancount v2, which beancount v3 no longer offers/exports?

**Comment by dallaslu** [comment]
Actually, I am still using the v2 version now. It will take some time to integrate v3.

**Comment by lvh** [comment]
FYI: v3 is now released, so people just doing `pip install beancount` will start getting v3 automatically. The error message here doesn't make it obvious that's a v2/v3 issue.

Also, good news: the API still exists, it's just that beancount has split up its functionality into different packages. It's now in beanprice: https://github.com/beancount/beanprice/blob/e894c9182f4d16f9a46ccb87bdaeca1a7dede040/beanprice/date_utils.py#L13

... which I'll admit doesn't make a ton of sense to me (date parsing is not specific to prices and this issue is a perfect example). I don't know how amenable beancount devs would be to this but I think it's a good reason to move it back.

Alternatively you could try/except wrap the import: it really is just a move, the code is otherwise identical.
